---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    expose: 'true'
    group: com.redhat.cloudnative
    version: 1.0.0-SNAPSHOT
  annotations:
    prometheus.io/path: /q/metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{ .Values.name }}
    group: com.redhat.cloudnative