ame: quickstart-scheduled
service_mesh_enabled: true
schedule: '"0 0 * * *"'
env: test
image:
  registry: <registryname>.azurecr.io #Point to your registry
  repository: quickstart-scheduled    #Point to your repository
  name: quickstart-scheduled          #Point to your image name
  version: latest                     #Define your version
config:
  loglevel: INFO
  cosmos:
    host: <cosmosdb your host>        #eg. https://sim-management.documents.azure.com:443/
    database: <your-database-name>    #eg. sim-management
    container: <your-container-name>  #eg. masterdata-poller-LastChangeIds
    partitionkey: <db key>            #eg. id
  kafka:
    cluster:
      name: wc-test-kafka-cluster
    user: quickstart-kafka-user
    outtopic: sim-state-manager
  ocp:
    cluster:
      domain: <YOUR-OCP-DOMAIN>       #OCP Domain eg. svc.cluster.local or apps.cluster.domain.com