apiVersion: v2 #helm v3
description: A Helm chart for the Quarkus Cronjob Quickstart
name: quickstart-lambda-to-quarkus-cronjob
version: 1.0.0
appVersion: v1.0.0
home: https://github.com/aws-lambdas-to-azure-quarkus-containers/quickstart-lambda-to-quarkus-cronjob.git
maintainers:
  - name: cloudnative-users

