name: quickstart-cronjob
schedule: '"* * * * *"'
image:
  registry: <your-registry>>.azurecr.io
  repository: quickstart-cronjob
  name: quickstart-cronjob
  version: latest
config:
  some:
    actor:
      name: 'Registering'
      domain: 'Test QA'
  loglevel: INFO
  cosmos: 
    database: token-cache
    partitionkey: clientId
    container: Tokens
