---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - resources:
            limits:
              cpu: '400m'
              memory: 1Gi
            requests:
              cpu: '200m'
              memory: 512Mi
          name: quarkus
          env:
            - name: kafka.ssl.truststore.password
              valueFrom:
                secretKeyRef:
                  key: ca.password
                  name: {{ .Values.config.kafka.cluster.name }}-cluster-ca-cert
            - name: kafka.ssl.keystore.password
              valueFrom:
                secretKeyRef:
                  key: user.password
                  name: {{ .Values.config.kafka.user }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 9779
              protocol: TCP
            - name: jolokia
              containerPort: 8778
              protocol: TCP
          imagePullPolicy: Always
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}
          volumeMounts:
          - name: {{ .Values.name }}-application-properties
            mountPath: /deployments/config
          - name: {{ .Values.config.kafka.user }}-key
            mountPath: /deployments/keystore            
          - name: {{ .Values.config.kafka.cluster.name }}-cluster-ca-cert
            mountPath: /deployments/truststore 
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: {{ .Values.name }}-application-properties
          configMap:
            name: {{ .Values.name }}-application-properties
        - name: {{ .Values.config.kafka.user }}-key
          secret:
            secretName: {{ .Values.config.kafka.user }}
        - name: {{ .Values.config.kafka.cluster.name }}-cluster-ca-cert
          secret:
            secretName: {{ .Values.config.kafka.cluster.name }}-cluster-ca-cert                                    
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
