---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ .Values.name }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: {{ .Values.name }}-application-properties
              configMap:
                name: {{ .Values.name }}-application-properties
          containers:
            - name: quarkus
              command:
                - java
                - '-jar'
                - /deployments/quarkus-run.jar
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: {{ .Values.name }}-application-properties
                  mountPath: /deployments/config
              envFrom:
                - secretRef:
                    name: {{ .Values.name }}-db-connection-details
              image: {{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.version }}
          restartPolicy: OnFailure